version: '3.8'

services:
  mysql-master1:
    image: mysql:8.0
    container_name: mysql-master1
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: repl_user
      MYSQL_PASSWORD: repl_password
    ports:
      - "3307:3306"
    volumes:
      - ./master1.cnf:/etc/mysql/conf.d/mysql.cnf
      - master1_data:/var/lib/mysql
    command: --server-id=1 --log-bin=mysql-bin --binlog-do-db=testdb
    networks:
      - mysql-network

  mysql-master2:
    image: mysql:8.0
    container_name: mysql-master2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
      MYSQL_USER: repl_user
      MYSQL_PASSWORD: repl_password
    ports:
      - "3308:3306"
    volumes:
      - ./master2.cnf:/etc/mysql/conf.d/mysql.cnf
      - master2_data:/var/lib/mysql
    command: --server-id=2 --log-bin=mysql-bin --binlog-do-db=testdb
    networks:
      - mysql-network

volumes:
  master1_data:
  master2_data:

networks:
  mysql-network:
    driver: bridge